# IMTK_API_DOC Makefile
# 
# $Id: Makefile,v 1.1 2001/09/25 17:33:55 clwyatt Exp $
#

# edit this for your particular configuration
include ../../makeinclude

all: 

clean:
		
realclean: 
	$(RM) *.html *.class *.gif *.tex *.db
	
install:
