function generalsetup(pos)
% QSAR tool's general parameter setup panel
%
% pos is the position of the main QSAR gui. 

global Mdat;
global userdata;
%[pos(1)+pos(3)+6,pos(2)+pos(4)-172,350,200]
if ~isfield(Mdat.hsetgui,'sFig')

sFig = figure('Name','General Setup',...
              'NumberTitle','off',...
              'Units','pixels',...
              'Position',[pos(1)+pos(3)+6,pos(2),350,160],...
              'ToolBar','none',...  
              'MenuBar','none',... 
              'Resize','off',...
              'DockControls','off');
set(sFig,'CloseRequestFcn',{@closesetup,sFig});
setupPanel = uipanel(sFig,'Units','pixels',...
                 'ForegroundColor','black','Position',[0,0,350,160]); 
             
%-------------------------                 
% PREPROCESS PANEL
%-------------------------   
FilterPanel = uipanel('BorderType','line',...
                 'BorderType','line','Units','pixels',...
                 'ForegroundColor','black','Position',[1,120,349,55]);  
txtcorrfilt= uicontrol(FilterPanel,'Style', 'text', ...
                         'String', 'Corr', 'Position', [235 5 27 20]);
handles.corrfilt= uicontrol(FilterPanel,'Style', 'edit', 'BackgroundColor','white',...
                         'String', userdata.corrfilt, 'Position', [263 10 30 20]);
txtstdfilt= uicontrol(FilterPanel,'Style', 'text', ...
                         'String', 'Std', 'Position', [295 5 25 20]);
handles.stdfilt= uicontrol(FilterPanel,'Style', 'edit', 'BackgroundColor','white',...
                         'String', userdata.stdfilt, 'Position', [321 10 29 20]);
txtscale= uicontrol(FilterPanel,'Style', 'text', ...
                         'String', 'Scale', 'Position', [112 5 38 20]);                     
handles.scaling = uicontrol(FilterPanel,'Style', 'popupmenu', 'Units','pixels',...
                        'String','None|Mahalanobis',...
                        'BackgroundColor','white',...
                        'Position',[151,10,80,20]);
txtmetric= uicontrol(FilterPanel,'Style', 'text', ...
                         'String', 'Metric', 'Position', [1 5 37 20]);                     
handles.metric = uicontrol(FilterPanel,'Style', 'popupmenu', 'Units','pixels',...
                        'String','Euclidian|Cosine|Dice|Hamming|Soergel|Tanimoto',...
                        'BackgroundColor','white',...
                        'Position',[39,10,70,20]);
%-------------------------                 
% OPERATIONAL PANEL
%-------------------------                    
OpPanel = uipanel('Title','Operational','BorderType','line',...
                 'BorderType','line','Units','pixels',...
                 'ForegroundColor','black','Position',[1,1,349,120]);  
txtvalid= uicontrol(OpPanel,'Style', 'text', ...
                         'String', 'Validation', 'Position', [1 80 70 20]);    
handles.validation = uicontrol(OpPanel,'Style', 'popupmenu', 'Units','pixels',...
                        'String','None|Leave-One-Out|Leave-Some-Out',...
                        'BackgroundColor','white',...
                        'Position',[75,85,110,20]);  
                    
userdata.partitionfile = get(Mdat.hgui.partitionfile, 'String');
if ~isempty(userdata.partitionfile)
    [rownames columnames Maskmat] = qsarimport(userdata.partitionfile);
    userdata.percentout = length(find(Maskmat(:,1)))/size(Maskmat,1)*100;
end;                       


txtout= uicontrol(OpPanel,'Style', 'text', ...
                         'String', 'Out%', 'Position', [1 45 43 20]);    
handles.percentout = uicontrol(OpPanel,'Style', 'edit', 'Units','pixels',...
                        'String',num2str(userdata.percentout),...
                        'BackgroundColor','white',...
                        'Position',[45,50,40,20]); 
txtnfold= uicontrol(OpPanel,'Style', 'text', ...
                         'String', 'N-Fold', 'Position', [95 45 45 20]);    
handles.nfold = uicontrol(OpPanel,'Style', 'edit', 'Units','pixels',...
                        'String',num2str(userdata.nfold),...
                        'BackgroundColor','white',...
                        'Position',[145,50,40,20]); 
txtoptimize= uicontrol(OpPanel,'Style', 'text', ...
                         'String', 'Optimize', 'Position', [1 5 70 20]);    
handles.optimize = uicontrol(OpPanel,'Style', 'popupmenu', 'Units','pixels',...
                        'String','Accuracy|RMSE|False Pos|False Neg',...
                        'BackgroundColor','white',...
                        'Position',[75,10,110,20]);                        
txtdesclimit= uicontrol(OpPanel,'Style', 'text', ...
                         'String', 'Desc. Size', 'Position', [195 80 65 20]);                     
handles.DescLimit = uicontrol(OpPanel,'Style', 'popupmenu', 'Units','pixels',...
                        'String','Max Limit|Fixed|Fixed Initial|None',...
                        'BackgroundColor','white',...
                        'Position',[265,85,85,20]);                        
txtdescrnum= uicontrol(OpPanel,'Style', 'text', ...
                         'String', 'Desc. Num', 'Position', [195 45 65 20]);                     
handles.DescNum = uicontrol(OpPanel,'Style', 'edit', 'Units','pixels',...
                        'String',num2str(userdata.Descriptors),'BackgroundColor','white',...
                        'Position',[265,50,85,20]);                       
          
handles.sreset = uicontrol(OpPanel,'Style', 'pushbutton', ...
     'String', 'Reset', 'Position', [300 1 45 25], ...
     'Callback',@setupreset);  
handles.sOk = uicontrol(OpPanel,'Style', 'pushbutton', ...
     'String', 'Done', 'Position', [250 1 45 25], ...
     'Callback',@setupOK);   
  
handles.sFig=sFig;
Mdat.hsetgui=handles;

else
    set(Mdat.hsetgui.sFig,'Position',[pos(1)+pos(3)+6,pos(2),350,160]);
    set(Mdat.hsetgui.sFig,'Visible','on');
end       

