function varselsetup(pos)
% QSAR tool's general parameter setup panel
%
% pos is the position of the main QSAR gui. 

global Mdat;
global userdata;

if ~isfield(Mdat.hVsetgui,'sVFig')

sVFig = figure('Name','Variable Selection Setup',...
              'NumberTitle','off',...
              'Units','pixels',...
              'Position',[pos(1)+pos(3)+6,pos(2)+pos(4)-85,350,112],...
              'ToolBar','none',...  
              'MenuBar','none',... 
              'Resize','off',...
              'DockControls','off');
set(sVFig,'CloseRequestFcn',{@closesetup,sVFig});

varselPanel = uipanel('Units','pixels',...
                 'ForegroundColor','black','Position',[0,0,350,112]); 
             
% Modeling method
varsel = get(Mdat.hgui.varsel, 'String');
varsel = deblank(varsel(get(Mdat.hgui.varsel, 'Value'),:));
switch varsel
case 'None'
    txtnone= uicontrol('Style', 'text', ...
                     'String', 'There is no adjustable parameter', 'Position', [5,20,200,20]);
case 'GA' 
    
   txtmin= uicontrol('Style', 'text', ...
                             'String', 'Min', 'Position', [45,95,25,15]); 
   txtmax= uicontrol('Style', 'text', ...
                             'String', 'Max', 'Position', [75,95,25,15]);                  
   txtmutate= uicontrol('Style', 'text', ...
                             'String', 'Mutate', 'Position', [2,70,40,20]);    
   handles.minmutate = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.MinMutate),...
                            'BackgroundColor','white',...
                            'Position',[45,75,25,20]);
   handles.maxmutate = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.MaxMutate),...
                            'BackgroundColor','white',...
                            'Position',[75,75,25,20]);    
   txtcross= uicontrol('Style', 'text', ...
                             'String', 'Cross', 'Position', [2,45,40,20]);    
   handles.mincross = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.MinCrossOver),...
                            'BackgroundColor','white',...
                            'Position',[45,50,25,20]);
   handles.maxcross = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.MaxCrossOver),...
                            'BackgroundColor','white',...
                            'Position',[75,50,25,20]); 
   txtpmutate= uicontrol('Style', 'text', ...
                             'String', 'Pmutate', 'Position', [2,25,50,15]);    
   handles.pmutate = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.Pmutation),...
                            'BackgroundColor','white',...
                            'Position',[55,25,45,20]);   
   txtpcross= uicontrol('Style', 'text', ...
                             'String', 'Pcross', 'Position', [2,2,50,15]);                       
   handles.pcross = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.Pcross),...
                            'BackgroundColor','white',...
                            'Position',[55,2,45,18]);  
   
   txtsubset= uicontrol('Style', 'text', ...
                             'String', 'Subset', 'Position', [165,95,45,15]);                
   txtsubpop= uicontrol('Style', 'text', ...
                             'String', 'Size', 'Position', [112,70,50,20]);    
   handles.subpop = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.SubsetPopulation),...
                            'BackgroundColor','white',...
                            'Position',[165,75,40,20]);
   txtcross= uicontrol('Style', 'text', ...
                             'String', 'Number', 'Position', [112,45,50,20]);    
   handles.subno = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.Subsets),...
                            'BackgroundColor','white',...
                            'Position',[165,50,40,20]); 

   txtgeneration= uicontrol('Style', 'text', ...
                             'String','Evolve', 'Position', [115,25,50,15]);    
   handles.generations = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.Generation),...
                            'BackgroundColor','white',...
                            'Position',[115,4,50,20]);                      
   txtelite= uicontrol('Style', 'text', ...
                             'String', 'Elite%', 'Position', [180,25,50,15]);    
   handles.elite = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.Elites),...
                            'BackgroundColor','white',...
                            'Position',[180,4,50,20]);        
   txtgenelife= uicontrol('Style', 'text', ...
                             'String', 'Gene Life', 'Position', [230,25,70,15]);    
   handles.GeneLife = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.GeneLife),...
                            'BackgroundColor','white',...
                            'Position',[235,4,50,20]);                             
                            
                        
   txtpool= uicontrol('Style', 'text', ...
                             'String', 'Pool', 'Position', [285,95,45,15]);   
   txtpooldur= uicontrol('Style', 'text', ...
                             'String', 'Length', 'Position', [232,70,50,20]);    
   handles.pooldur = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.PoolDur),...
                            'BackgroundColor','white',...
                            'Position',[285,75,40,20]); 
   txtpoolfreq= uicontrol('Style', 'text', ...
                             'String','Freq', 'Position', [232,45,50,20]);    
   handles.poolfreq = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.PoolFreq),...
                            'BackgroundColor','white',...
                            'Position',[285,50,40,20]);
                        
case 'Hill Climbing'
   txtgeneration= uicontrol('Style', 'text', ...
                             'String', 'Generations', 'Position', [3,80,80,20]);    
   handles.generations = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.HGeneration),...
                            'BackgroundColor','white',...
                            'Position',[85,85,55,20]);
   txtmutation= uicontrol('Style', 'text', ...
                             'String', 'Mutations', 'Position', [150,80,60,20]);                     
   handles.mutation = uicontrol('Style', 'edit', 'Units','pixels',...
                            'BackgroundColor','white',...
                            'String',num2str(userdata.Mutate),...
                            'Position',[215,85,35,20]);
   txtHcycle= uicontrol('Style', 'text', ...
                             'String', 'Cycle', 'Position', [255,80,50,20]);                     
   handles.Hcycle = uicontrol('Style', 'edit', 'Units','pixels',...
                            'BackgroundColor','white',...
                            'String',num2str(userdata.Hcycle),...
                            'Position',[310,85,35,20]);
case 'SA'
   txttstart= uicontrol('Style', 'text', ...
                             'String', 'Tstart', 'Position', [3,70,50,20]);    
   handles.tstart = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.StartT),...
                            'BackgroundColor','white',...
                            'Position',[55,75,55,20]);
   txttstop= uicontrol('Style', 'text', ...
                             'String', 'Tstop', 'Position', [120,70,40,20]);                     
   handles.tstop = uicontrol('Style', 'edit', 'Units','pixels',...
                            'BackgroundColor','white',...
                            'String',num2str(userdata.EndT),...
                            'Position',[165,75,55,20]);
   txtdroprate= uicontrol('Style', 'text', ...
                            'String', 'Drop Rate', 'Position', [230,70,70,20]);                     
   handles.droprate = uicontrol('Style', 'edit', 'Units','pixels','BackgroundColor','white',...
                            'String',num2str(userdata.Droprate),...
                            'Position',[305,75,40,20]); 
   txtcycle= uicontrol('Style', 'text', ...
                             'String', 'Cycle', 'Position', [3,40,50,20]);    
   handles.cycle = uicontrol('Style', 'edit', 'Units','pixels',...
                            'String',num2str(userdata.Cycle),...
                            'BackgroundColor','white',...
                            'Position',[55,45,55,20]);
   txtmutation= uicontrol('Style', 'text', ...
                             'String', 'Mutations', 'Position', [120,40,60,20]);                     
   handles.mutation = uicontrol('Style', 'edit', 'Units','pixels',...
                            'BackgroundColor','white',...
                            'String',num2str(userdata.Mutate),...
                            'Position',[185,45,35,20]);
    
case 'Stepwise'    
    
end   

%-------------------------                 
% PREPROCESS PANEL
%-------------------------   

handles.sreset = uicontrol(sVFig,'Style', 'pushbutton', ...
     'String', 'Reset', 'Position', [300 1 45 25], ...
     'Callback',@varselreset);   
  
handles.sVFig=sVFig;
Mdat.hVsetgui=handles;

else
    set(Mdat.hVsetgui.sVFig,'Position',[pos(1)+pos(3)+6,pos(2)+pos(4)-85,350,112]);
    set(Mdat.hVsetgui.sVFig,'Visible','on');
end       


