#######################################################################################
# File: Makefile
# Abstract: makefile for capd project
# Created: 2002-06-24
# (C) 2002 by Wake Forest University School of Medicine
#                             and
#         Virgina Polytechnic Institute and State University
#
# Last Revision ($Revision: 1.1.1.1 $) by $Author: hongli $ on $Date: 2002/12/06 21:49:34 $
#######################################################################################

include ../makeinclude
	
clean: 
	$(RM) api/html/*
	$(RM) api/latex/*
	
realclean: clean 

install:

